# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc


alias c='clear'
alias ..='cd ..'
alias l='ls'
alias ll='ls -l'
alias e='exit'
alias nf='mkdir'
alias df='rm -r'
alias sub="cd  C:\Program\ Files\Sublime\ Text/sublime_text"
alias gc="git clone"
alias pg="flutter pub get"
ae(){
path=echo `pwd`
    cd ~
    nano .bash_profile
cd $path
}

ac()
{
    git add .
    git commit -m "$1"
}

gg()
{
git add .
git commit -m "$1"
if [[ -z  $2 ]]
then
git push -u origin main
else
git push -u origin $2
fi
}




PS1='┌──[ꜱᴋɪʟʟZ ✨] \n└──╼[\W] ➤➤  '

