export DOTFILES=/Users/narayan/projects/narayann7/dotfiles
# DOTFILES is the path is auto generated by the install.sh

# welcome script
python3 "$DOTFILES/scripts/py/welcome.py"

# all variables used in shell and scripts
source "$DOTFILES/zsh/variables.zsh"

# oh my zsh plugins
plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    # zsh-autocomplete
)

# all scouces
source "$DOTFILES/zsh/source.zsh"

# all aliases
source "$DOTFILES/zsh/.aliases"

# configure zsh
source "$DOTFILES/zsh/config.zsh"


#function execute only when shell is closed
function shellExit {
    # to remove the remove_duplicate_commands for zsh_history
    zsh "$DOTFILES/scripts/shell/remove_duplicate_commands.zsh"
}

trap shellExit EXIT

eval "$(atuin init zsh --disable-up-arrow)"
bindkey '^r' atuin-search
